language: rust
rust: stable
env:
  global:
    - TARGET_BUILD=thumbv7em-none-eabi
    - RUSTFLAGS="--deny warnings"

install:
  - rustup target add $TARGET_BUILD
  - rustup component add rustfmt

stages:
  - test

jobs:
  include:
    - stage: test
      script:
        - cargo fmt --all -- --check
        - cd $TRAVIS_BUILD_DIR/homekit && cargo test
        - cd $TRAVIS_BUILD_DIR/homekit-demo && cargo build --target $TARGET_BUILD

notifications:
  email:
    on_success: never
